version: "2.2"
services:
    website:
        container_name: blogbuilder
        image: blogbuilder
        environment:
            - VIRTUAL_HOST=build.rolandw.dev
            - LETSENCRYPT_HOST=build.rolandw.dev
            - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
            - VIRTUAL_PORT=3000
            - VIRTUAL_NETWORK=nginx-proxy
        volumes:
            - ./content:/usr/src/app/content
            - ./app/dist:/usr/src/app/dist
            - ./app:/usr/src/app

networks:
    default:
        external:
            name: gateway_network
