version: "2.2"
services:
    blog:
        image: nginx:alpine
        container_name: blog
        restart: unless-stopped
        environment:
           - VIRTUAL_HOST=blog.rolandw.dev
           - LETSENCRYPT_HOST=blog.rolandw.dev
           - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
           - VIRTUAL_PORT=3000
           - VIRTUAL_NETWORK=nginx-proxy
        tty: true
        volumes:
           - ./app/dist:/usr/share/nginx/html
          #- ./nginx/conf.d/:/etc/nginx/conf.d/

networks:
    default:
        external:
            name: nginx-proxy
